<x-app-layout>

    

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            

{{-- ====================================== --}}
{{-- SECTION 1 : HERO HEADER --}}
{{-- ====================================== --}}

<div class="mb-8 overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">

    <div class="flex flex-col gap-6 p-8 lg:flex-row lg:items-center lg:justify-between">

        <div class="flex items-start gap-5">

            <div class="flex h-16 w-16 items-center justify-center rounded-2xl bg-pink-100 text-pink-600">

                <svg xmlns="http://www.w3.org/2000/svg"
                     class="h-8 w-8"
                     fill="none"
                     viewBox="0 0 24 24"
                     stroke="currentColor"
                     stroke-width="1.8">

                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M21.75 6.75v10.5A2.25 2.25 0 0 1 19.5 19.5H4.5a2.25 2.25 0 0 1-2.25-2.25V6.75A2.25 2.25 0 0 1 4.5 4.5h15A2.25 2.25 0 0 1 21.75 6.75Z"/>

                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          d="m3 7.5 8.291 5.527a1.25 1.25 0 0 0 1.418 0L21 7.5"/>

                </svg>

            </div>

            <div>

                <p class="text-sm font-semibold uppercase tracking-widest text-pink-600">
                    Communication Center
                </p>

                <h1 class="mt-1 text-3xl font-bold tracking-tight text-gray-900">
                    SMS Notification History
                </h1>

                <p class="mt-3 max-w-3xl text-sm leading-6 text-gray-500">
                    View and monitor all SMS reminders generated by CareCradle for maternal appointments.
                    Track delivery status, notification history, and communication records from one centralized dashboard.
                </p>

            </div>

        </div>

        <div class="rounded-2xl border border-pink-100 bg-pink-50 px-5 py-4">

            <div class="flex items-center gap-3">

                <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-pink-100 text-pink-600">

                    <svg xmlns="http://www.w3.org/2000/svg"
                         class="h-5 w-5"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke="currentColor"
                         stroke-width="1.8">

                        <path stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M21.75 6.75v10.5A2.25 2.25 0 0 1 19.5 19.5H4.5a2.25 2.25 0 0 1-2.25-2.25V6.75A2.25 2.25 0 0 1 4.5 4.5h15A2.25 2.25 0 0 1 21.75 6.75Z"/>

                        <path stroke-linecap="round"
                              stroke-linejoin="round"
                              d="m3 7.5 8.291 5.527a1.25 1.25 0 0 0 1.418 0L21 7.5"/>

                    </svg>

                </div>

                <div>

                    <p class="text-xs font-semibold uppercase tracking-wide text-pink-600">
                        CareCradle EMR
                    </p>

                    <p class="text-sm font-semibold text-gray-900">
                        SMS Notifications
                    </p>

                </div>

            </div>

        </div>

    </div>

</div>

{{-- ====================================== --}}
{{-- SECTION 2 : SUMMARY STATISTICS --}}
{{-- ====================================== --}}

@php
    $totalNotifications = $notifications->count();
    $pendingNotifications = $notifications->where('status', 'Pending')->count();
    $sentNotifications = $notifications->where('status', 'Sent')->count();
    $failedNotifications = $notifications->where('status', 'Failed')->count();
@endphp

<div class="grid grid-cols-1 gap-6 mb-8 sm:grid-cols-2 xl:grid-cols-4">

    {{-- Total Notifications --}}
    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">

        <div class="flex items-center justify-between">

            <div>

                <p class="text-sm font-medium text-gray-500">
                    Total Notifications
                </p>

                <h3 class="mt-2 text-3xl font-bold text-gray-900">
                    {{ $totalNotifications }}
                </h3>

                <p class="mt-1 text-sm text-gray-500">
                    SMS records
                </p>

            </div>

            <div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-pink-100 text-pink-600">

                <svg xmlns="http://www.w3.org/2000/svg"
                     class="h-7 w-7"
                     fill="none"
                     viewBox="0 0 24 24"
                     stroke="currentColor"
                     stroke-width="1.8">

                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M21.75 6.75v10.5A2.25 2.25 0 0 1 19.5 19.5H4.5a2.25 2.25 0 0 1-2.25-2.25V6.75A2.25 2.25 0 0 1 4.5 4.5h15A2.25 2.25 0 0 1 21.75 6.75Z"/>

                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          d="m3 7.5 8.291 5.527a1.25 1.25 0 0 0 1.418 0L21 7.5"/>

                </svg>

            </div>

        </div>

    </div>

    {{-- Pending --}}
    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">

        <div class="flex items-center justify-between">

            <div>

                <p class="text-sm font-medium text-gray-500">
                    Pending
                </p>

                <h3 class="mt-2 text-3xl font-bold text-yellow-600">
                    {{ $pendingNotifications }}
                </h3>

                <p class="mt-1 text-sm text-gray-500">
                    Awaiting delivery
                </p>

            </div>

            <div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-yellow-100 text-yellow-600">

                <svg xmlns="http://www.w3.org/2000/svg"
                     class="h-7 w-7"
                     fill="none"
                     viewBox="0 0 24 24"
                     stroke="currentColor"
                     stroke-width="1.8">

                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M12 9v3.75m0 3.75h.007v.008H12v-.008ZM21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>

                </svg>

            </div>

        </div>

    </div>

    {{-- Sent --}}
    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">

        <div class="flex items-center justify-between">

            <div>

                <p class="text-sm font-medium text-gray-500">
                    Sent
                </p>

                <h3 class="mt-2 text-3xl font-bold text-green-600">
                    {{ $sentNotifications }}
                </h3>

                <p class="mt-1 text-sm text-gray-500">
                    Successfully delivered
                </p>

            </div>

            <div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-green-100 text-green-600">

                <svg xmlns="http://www.w3.org/2000/svg"
                     class="h-7 w-7"
                     fill="none"
                     viewBox="0 0 24 24"
                     stroke="currentColor"
                     stroke-width="1.8">

                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          d="m4.5 12.75 6 6 9-13.5"/>

                </svg>

            </div>

        </div>

    </div>

    {{-- Failed --}}
    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">

        <div class="flex items-center justify-between">

            <div>

                <p class="text-sm font-medium text-gray-500">
                    Failed
                </p>

                <h3 class="mt-2 text-3xl font-bold text-red-600">
                    {{ $failedNotifications }}
                </h3>

                <p class="mt-1 text-sm text-gray-500">
                    Delivery unsuccessful
                </p>

            </div>

            <div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-red-100 text-red-600">

                <svg xmlns="http://www.w3.org/2000/svg"
                     class="h-7 w-7"
                     fill="none"
                     viewBox="0 0 24 24"
                     stroke="currentColor"
                     stroke-width="1.8">

                    <path stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M6 18 18 6M6 6l12 12"/>

                </svg>

            </div>

        </div>

    </div>

</div>
{{-- ====================================== --}}
{{-- SECTION 3 : SEARCH BAR --}}
{{-- ====================================== --}}

<div class="mb-8">

    <div class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">

        {{-- Header --}}
        <div class="border-b border-gray-200 bg-gray-50 px-6 py-5">

            <div class="flex items-center gap-3">

                <div class="flex h-11 w-11 items-center justify-center rounded-xl bg-pink-100 text-pink-600">

                    <svg xmlns="http://www.w3.org/2000/svg"
                         class="h-6 w-6"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke="currentColor"
                         stroke-width="1.8">

                        <path stroke-linecap="round"
                              stroke-linejoin="round"
                              d="m21 21-4.35-4.35m1.35-5.4a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/>

                    </svg>

                </div>

                <div>

                    <h2 class="text-lg font-semibold text-gray-900">
                        Search SMS Notifications
                    </h2>

                    <p class="mt-1 text-sm text-gray-500">
                        Search notification records using the recipient number, mother's name, notification type, or delivery status.
                    </p>

                </div>

            </div>

        </div>

        {{-- Body --}}
        <div class="p-6">

            <form method="GET" action="{{ route('sms-notifications.index') }}">

                <div class="flex flex-col gap-4 lg:flex-row lg:items-center">

                    <div class="relative flex-1">

                        <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-4">

                            <svg xmlns="http://www.w3.org/2000/svg"
                                 class="h-5 w-5 text-gray-400"
                                 fill="none"
                                 viewBox="0 0 24 24"
                                 stroke="currentColor"
                                 stroke-width="1.8">

                                <path stroke-linecap="round"
                                      stroke-linejoin="round"
                                      d="m21 21-4.35-4.35m1.35-5.4a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/>

                            </svg>

                        </div>

                        <input
                            type="text"
                            name="search"
                            value="{{ request('search') }}"
                            placeholder="Search recipient number, mother name, notification type, or delivery status..."
                            class="w-full rounded-2xl border border-gray-300 bg-gray-50 py-3 pl-12 pr-4 text-sm text-gray-700 placeholder:text-gray-400 transition duration-200 focus:border-pink-600 focus:bg-white focus:outline-none focus:ring-4 focus:ring-pink-100">

                    </div>

                    <div class="flex flex-col gap-3 sm:flex-row">

                        {{-- Search --}}
                        <button
                            type="submit"
                            class="inline-flex items-center justify-center gap-2 rounded-xl bg-pink-600 px-6 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-pink-700">

                            <svg xmlns="http://www.w3.org/2000/svg"
                                 class="h-5 w-5"
                                 fill="none"
                                 viewBox="0 0 24 24"
                                 stroke="currentColor"
                                 stroke-width="1.8">

                                <path stroke-linecap="round"
                                      stroke-linejoin="round"
                                      d="m21 21-4.35-4.35m1.35-5.4a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/>

                            </svg>

                            Search

                        </button>

                        {{-- Reset --}}
                        @if(request('search'))

                            <a
                                href="{{ route('sms-notifications.index') }}"
                                class="inline-flex items-center justify-center gap-2 rounded-xl border border-gray-300 bg-white px-6 py-3 text-sm font-semibold text-gray-700 transition hover:bg-gray-50">

                                <svg xmlns="http://www.w3.org/2000/svg"
                                     class="h-5 w-5"
                                     fill="none"
                                     viewBox="0 0 24 24"
                                     stroke="currentColor"
                                     stroke-width="1.8">

                                    <path stroke-linecap="round"
                                          stroke-linejoin="round"
                                          d="M4.5 12a7.5 7.5 0 0 1 12.89-5.303M19.5 4.5v6h-6"/>

                                </svg>

                                Reset

                            </a>

                        @endif

                    </div>

                </div>

            </form>

            {{-- Search Tips --}}
            <div class="mt-5 flex flex-wrap gap-2">

                <span class="rounded-full bg-pink-50 px-3 py-1 text-xs font-medium text-pink-700">
                    Recipient Number
                </span>

                <span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700">
                    Mother Name
                </span>

                <span class="rounded-full bg-green-50 px-3 py-1 text-xs font-medium text-green-700">
                    Notification Type
                </span>

                <span class="rounded-full bg-orange-50 px-3 py-1 text-xs font-medium text-orange-700">
                    Delivery Status
                </span>

            </div>

        </div>

    </div>

</div>
{{-- ====================================== --}}
{{-- SECTION 4 : SMS NOTIFICATIONS TABLE --}}
{{-- ====================================== --}}

@if($notifications->count())

<div class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">

    {{-- Table Header --}}
    <div class="border-b border-gray-200 bg-gray-50 px-6 py-5">

        <div class="flex items-center justify-between">

            <div>

                <h2 class="text-lg font-semibold text-gray-900">
                    SMS Notification Records
                </h2>

                <p class="mt-1 text-sm text-gray-500">
                    Complete history of SMS reminders generated by CareCradle.
                </p>

            </div>

            <div class="rounded-xl border border-pink-100 bg-pink-50 px-4 py-2">

                <span class="text-sm font-semibold text-pink-700">
                    {{ $notifications->count() }} Record(s)
                </span>

            </div>

        </div>

    </div>

    <div class="overflow-x-auto">

        <table class="min-w-full divide-y divide-gray-200">

            <thead class="bg-gray-50">

                <tr>

                    <th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">
                        Recipient
                    </th>

                    <th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">
                        Mother
                    </th>

                    <th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">
                        Notification Type
                    </th>

                   <th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">
    Status
</th>

<th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">
    Failure Reason
</th>

<th class="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">
    Sent Date & Time
</th>

                    <th class="px-6 py-4 text-center text-xs font-semibold uppercase tracking-wider text-gray-500">
                        Actions
                    </th>

                </tr>

            </thead>

            <tbody class="divide-y divide-gray-100 bg-white">

                @foreach($notifications as $notification)

                    @php

                        $statusClasses = match($notification->status) {

                            'Pending' => 'bg-yellow-100 text-yellow-700 border border-yellow-200',

                            'Sent' => 'bg-green-100 text-green-700 border border-green-200',

                            'Failed' => 'bg-red-100 text-red-700 border border-red-200',

                            default => 'bg-gray-100 text-gray-700 border border-gray-200',

                        };

                    @endphp

                    <tr class="transition duration-200 hover:bg-gray-50">

                        {{-- Recipient --}}
                        <td class="px-6 py-5 whitespace-nowrap">

                            <div>

                                <p class="font-semibold text-gray-900">
                                    {{ $notification->recipient_number }}
                                </p>

                                <p class="text-sm text-gray-500">
                                    Mobile Number
                                </p>

                            </div>

                        </td>

                        {{-- Mother --}}
                        <td class="px-6 py-5 whitespace-nowrap">

                            <div>

                                <p class="font-semibold text-gray-900">

                                    {{ $notification->mother->first_name }}
                                    {{ $notification->mother->last_name }}

                                </p>

                                <p class="text-sm text-gray-500">
                                    Mother Record
                                </p>

                            </div>

                        </td>

                        {{-- Notification Type --}}
                        <td class="px-6 py-5 whitespace-nowrap">

                            <span class="inline-flex rounded-full bg-blue-50 px-3 py-1 text-sm font-medium text-blue-700">

                                {{ $notification->notification_type }}

                            </span>

                        </td>

                        {{-- Status --}}
                        <td class="px-6 py-5 whitespace-nowrap">

                            <span class="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-semibold {{ $statusClasses }}">

                                @switch($notification->status)

                                    @case('Pending')

                                        <span class="h-2.5 w-2.5 rounded-full bg-yellow-500"></span>

                                        Pending

                                        @break

                                    @case('Sent')

                                        <span class="h-2.5 w-2.5 rounded-full bg-green-500"></span>

                                        Sent

                                        @break

                                    @case('Failed')

                                        <span class="h-2.5 w-2.5 rounded-full bg-red-500"></span>

                                        Failed

                                        @break

                                    @default

                                        {{ $notification->status }}

                                @endswitch

                            </span>

                        </td>

                        {{-- Failure Reason --}}
<td class="px-6 py-5">

    @if($notification->status === 'Failed')

        <div class="max-w-xs">

            <p class="text-sm font-medium text-red-600 break-words">
               {{ $notification->error_message ?? '—' }}
            </p>

        </div>

    @else

        <span class="text-gray-400 italic">
            —
        </span>

    @endif

</td>

                        {{-- Sent At --}}
                        <td class="px-6 py-5 whitespace-nowrap">

                            @if($notification->sent_at)

                                <div>

                                    <p class="font-medium text-gray-900">

                                        {{ \Carbon\Carbon::parse($notification->sent_at)->format('M d, Y') }}

                                    </p>

                                    <p class="text-sm text-gray-500">

                                        {{ \Carbon\Carbon::parse($notification->sent_at)->format('g:i A') }}

                                    </p>

                                </div>

                            @else

                                <span class="italic text-gray-400">

                                    —

                                </span>

                            @endif

                        </td>
{{-- Action --}}
<td class="px-6 py-5 text-center whitespace-nowrap">

    <div class="flex justify-center gap-2">

        {{-- View --}}
        <a
            href="{{ route('sms-notifications.show', $notification->id) }}"
            class="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 hover:shadow-md">

            <svg xmlns="http://www.w3.org/2000/svg"
                 class="h-5 w-5"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke="currentColor"
                 stroke-width="1.8">

                <path stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M2.25 12S5.25 5.25 12 5.25 21.75 12 21.75 12 18.75 18.75 12 18.75 2.25 12 2.25 12Z"/>

                <path stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M12 15.75A3.75 3.75 0 1 0 12 8.25a3.75 3.75 0 0 0 0 7.5Z"/>

            </svg>

            View

        </a>

        {{-- Send SMS --}}
        @if($notification->status == 'Pending')

            <form method="POST"
                  action="{{ route('sms-notifications.send', $notification) }}">

                @csrf

                <button
                    type="submit"
                    class="inline-flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-green-700 hover:shadow-md">

                    Send

                </button>

            </form>

        @endif

    </div>

</td>
                      
                    </tr>

                @endforeach

            </tbody>

        </table>

    </div>

    {{-- Preserve Existing Pagination --}}
    <div class="border-t border-gray-200 bg-white px-6 py-5">

        {{ $notifications->links() }}

    </div>

</div>



{{-- ====================================== --}}
{{-- SECTION 5 : EMPTY STATE --}}
{{-- ====================================== --}}

@else

<div class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">

    <div class="flex flex-col items-center justify-center px-8 py-20 text-center">

        <div class="flex h-24 w-24 items-center justify-center rounded-3xl bg-pink-100 text-pink-600">

            <svg xmlns="http://www.w3.org/2000/svg"
                 class="h-12 w-12"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke="currentColor"
                 stroke-width="1.8">

                <path stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M21.75 6.75v10.5A2.25 2.25 0 0 1 19.5 19.5H4.5a2.25 2.25 0 0 1-2.25-2.25V6.75A2.25 2.25 0 0 1 4.5 4.5h15A2.25 2.25 0 0 1 21.75 6.75Z"/>

                <path stroke-linecap="round"
                      stroke-linejoin="round"
                      d="m3 7.5 8.291 5.527a1.25 1.25 0 0 0 1.418 0L21 7.5"/>

            </svg>

        </div>

        <h2 class="mt-8 text-2xl font-bold text-gray-900">
            No SMS Notifications Found
        </h2>

        <p class="mt-3 max-w-2xl text-gray-500 leading-7">
            There are currently no SMS notification records available in the system.
            SMS reminders will automatically appear here once appointments are created
            and notification messages are generated by the CareCradle Maternal & Infant
            Health Monitoring System.
        </p>

        <div class="mt-10 grid w-full max-w-3xl gap-4 md:grid-cols-3">

            <div class="rounded-2xl border border-gray-200 bg-gray-50 p-5">

                <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-pink-100 text-pink-600">

                    <svg xmlns="http://www.w3.org/2000/svg"
                         class="h-6 w-6"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke="currentColor"
                         stroke-width="1.8">

                        <path stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M12 6v6h4.5"/>

                        <path stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>

                    </svg>

                </div>

                <h3 class="mt-4 font-semibold text-gray-900">
                    Schedule Appointments
                </h3>

                <p class="mt-2 text-sm text-gray-500">
                    SMS reminders are generated from scheduled maternal appointments.
                </p>

            </div>

            <div class="rounded-2xl border border-gray-200 bg-gray-50 p-5">

                <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-blue-100 text-blue-600">

                    <svg xmlns="http://www.w3.org/2000/svg"
                         class="h-6 w-6"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke="currentColor"
                         stroke-width="1.8">

                        <path stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M21.75 6.75v10.5A2.25 2.25 0 0 1 19.5 19.5H4.5a2.25 2.25 0 0 1-2.25-2.25V6.75A2.25 2.25 0 0 1 4.5 4.5h15A2.25 2.25 0 0 1 21.75 6.75Z"/>

                        <path stroke-linecap="round"
                              stroke-linejoin="round"
                              d="m3 7.5 8.291 5.527a1.25 1.25 0 0 0 1.418 0L21 7.5"/>

                    </svg>

                </div>

                <h3 class="mt-4 font-semibold text-gray-900">
                    Automatic SMS
                </h3>

                <p class="mt-2 text-sm text-gray-500">
                    CareCradle automatically prepares reminder messages for patients.
                </p>

            </div>

            <div class="rounded-2xl border border-gray-200 bg-gray-50 p-5">

                <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-green-100 text-green-600">

                    <svg xmlns="http://www.w3.org/2000/svg"
                         class="h-6 w-6"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke="currentColor"
                         stroke-width="1.8">

                        <path stroke-linecap="round"
                              stroke-linejoin="round"
                              d="m4.5 12.75 6 6 9-13.5"/>

                    </svg>

                </div>

                <h3 class="mt-4 font-semibold text-gray-900">
                    Delivery Monitoring
                </h3>

                <p class="mt-2 text-sm text-gray-500">
                    Successfully delivered, pending, and failed notifications will appear here.
                </p>

            </div>

        </div>

    </div>

</div>

@endif

                

</x-app-layout>